# Generated by Django 4.2.5 on 2023-09-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.CharField(blank=True, max_length=255, verbose_name='картинка'),
        ),
    ]
