# Generated by Django 4.2.5 on 2023-09-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='quantity',
            new_name='amount',
        ),
    ]
