# Generated by Django 4.2.5 on 2023-09-09 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_options_alter_recipe_options_and_more'),
        ('users', '0002_alter_myuser_own_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cart', to='recipes.recipe', verbose_name='корзина'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='favorite_recipes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_favorite_recipes', to='recipes.recipe', verbose_name='любимый рецепт'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='own_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_id', to='recipes.recipe', verbose_name='мой рецепт'),
        ),
    ]
